var binToReg = {
    '00000' : '$zero',
    '00001' : '$at',
    '00010' : '$v0',
    '00011' : '$v1',
    '00100' : '$a0',
    '00101' : '$a1',
    '00110' : '$a2',
    '00111' : '$a3',
    '01000' : '$t0',
    '01001' : '$t1',
    '01010' : '$t2',
    '01011' : '$t3',
    '01100' : '$t4',
    '01101' : '$t5',
    '01110' : '$t6',
    '01111' : '$t7',
    '10000' : '$s0',
    '10001' : '$s1',
    '10010' : '$s2',
    '10011' : '$s3',
    '10100' : '$s4',
    '10101' : '$s5',
    '10110' : '$s6',
    '10111' : '$s7',
    '11000' : '$t8',
    '11001' : '$t9',
    '11010' : '$k0',
    '11011' : '$k1',
    '11100' : '$gp',
    '11101' : '$sp',
    '11110' : '$fp',
    '11111' : '$ra',
}

var opcodeToInst = {
    '000100' : {format: 'beq rs, rt, imm', hasRS: true, hasRT: true},
    '000101' : {format: 'bne rs, rt, imm', hasRS: true, hasRT: true},
    '000110' : {format: 'blez rs, imm', hasRS: true, hasRT: false},
    '000111' : {format: 'bgtz rs, imm', hasRS: true, hasRT: false},
    '001000' : {format: 'addi rt, rs, imm', hasRS: true, hasRT: true},
    '001001' : {format: 'addiu rt, rs, imm', hasRS: true, hasRT: true},
    '001010' : {format: 'slti rt, rs, imm', hasRS: true, hasRT: true},
    '001011' : {format: 'sltiu rt, rs, imm', hasRS: true, hasRT: true},
    '001100' : {format: 'andi rt, rs, imm', hasRS: true, hasRT: true},
    '001101' : {format: 'ori rt, rs, imm', hasRS: true, hasRT: true},
    '001110' : {format: 'xori rt, rs, imm', hasRS: true, hasRT: true},
    '001111' : {format: 'lui rt, imm', hasRS: false, hasRT: true},
    '100000' : {format: 'lb rt, imm(rs)', hasRS: true, hasRT: true},
    '100001' : {format: 'lh rt, imm(rs)', hasRS: true, hasRT: true},
    '100010' : {format: 'lw rt, imm(rs)', hasRS: true, hasRT: true},
    '100100' : {format: 'lbu rt, imm(rs)', hasRS: true, hasRT: true},
    '100101' : {format: 'lhu rt, imm(rs)', hasRS: true, hasRT: true},
    '101000' : {format: 'sb rt, imm(rs)', hasRS: true, hasRT: true},
    '101001' : {format: 'sh rt, imm(rs)', hasRS: true, hasRT: true},
    '101011' : {format: 'sw rt, imm(rs)', hasRS: true, hasRT: true}
}

var functToInst = {
    '000000' : {format: 'sll rd, rt, shamt', hasRS: false, hasRT: true, hasRD: true, hasShamt: true},
    '000010' : {format: 'srl rd, rt, shamt', hasRS: false, hasRT: true, hasRD: true, hasShamt: true},
    '000011' : {format: 'sra rd, rt, shamt', hasRS: false, hasRT: true, hasRD: true, hasShamt: true},
    '000100' : {format: 'sllv rd, rt, rs', hasRS: true, hasRT: true, hasRD: true, hasShamt: false},
    '000110' : {format: 'srlv rd, rt, rs', hasRS: true, hasRT: true, hasRD: true, hasShamt: false},
    '000111' : {format: 'srav rd, rt, rs', hasRS: true, hasRT: true, hasRD: true, hasShamt: false},
    '001000' : {format: 'jr rs', hasRS: true, hasRT: false, hasRD: false, hasShamt: false},
    '001001a' : {format: 'jalr rd, rs', hasRS: true, hasRT: false, hasRD: true, hasShamt: false}, // CAN BE jalr rs IF rd = 31 SUPPLIED, CHECK IT
    '001001b' : {format: 'jalr rs', hasRS: true, hasRT: false, hasRD: false, hasShamt: false},
    '001100' : {format: 'syscall', hasRS: false, hasRT: false, hasRD: false, hasShamt: false},
    '010000' : {format: 'mfhi rd', hasRS: false, hasRT: false, hasRD: true, hasShamt: false},
    '010001' : {format: 'mthi rs', hasRS: true, hasRT: false, hasRD: false, hasShamt: false},
    '010010' : {format: 'mflo rd', hasRS: false, hasRT: false, hasRD: true, hasShamt: false},
    '010011' : {format: 'mtlo rs', hasRS: true, hasRT: false, hasRD: false, hasShamt: false},
    '011000' : {format: 'mult rs, rt', hasRS: true, hasRT: true, hasRD: false, hasShamt: false},
    '011001' : {format: 'multu rs, rt', hasRS: true, hasRT: true, hasRD: false, hasShamt: false},
    '011010' : {format: 'div rs, rt', hasRS: true, hasRT: true, hasRD: false, hasShamt: false},
    '011011' : {format: 'divu rs, rt', hasRS: true, hasRT: true, hasRD: false, hasShamt: false},
    '100000' : {format: 'add rd, rs, rt', hasRS: true, hasRT: true, hasRD: true, hasShamt: false},
    '100001' : {format: 'addu rd, rs, rt', hasRS: true, hasRT: true, hasRD: true, hasShamt: false},
    '100010' : {format: 'sub rd, rs, rt', hasRS: true, hasRT: true, hasRD: true, hasShamt: false},
    '100011' : {format: 'subu rd, rs, rt', hasRS: true, hasRT: true, hasRD: true, hasShamt: false},
    '100100' : {format: 'and rd, rs, rt', hasRS: true, hasRT: true, hasRD: true, hasShamt: false},
    '100101' : {format: 'or rd, rs, rt', hasRS: true, hasRT: true, hasRD: true, hasShamt: false},
    '100110' : {format: 'xor rd, rs, rt', hasRS: true, hasRT: true, hasRD: true, hasShamt: false},
    '100111' : {format: 'nor rd, rs, rt', hasRS: true, hasRT: true, hasRD: true, hasShamt: false},
    '101010' : {format: 'slt rd, rs, rt', hasRS: true, hasRT: true, hasRD: true, hasShamt: false},
    '101011' : {format: 'sltu rd, rs, rt', hasRS: true, hasRT: true, hasRD: true, hasShamt: false}
}

module.exports = {
    binToReg: binToReg,
    opcodeToInst: opcodeToInst,
    functToInst: functToInst
}